name: docker image build

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: kiwilmao/firstimage:latest 

      - name: Verify Pushed Image
        run: docker pull kiwilmao/firstimage:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull 100xdevs/firstimage:latest
            sudo docker stop firstimage || true
            sudo docker rm firstimage || true
            sudo docker run -d --name firstimage -p 3005:3000 100xdevs/firstimage:latest